spring.application.name=cafe-uni

spring.datasource.url=jdbc:mysql://localhost:3306/menu_cafeteria2
spring.datasource.username=root
spring.datasource.password=Radiohead4265@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true